name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, v18.7, 18.x, v18.16.0, '*']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: 'npm'
          cache-dependency-path: 'package.json'

      - run: npm install
      - run: npm run ci-tests

      - name: Deploy docs
        if: github.ref == 'refs/heads/main' && matrix.node-version == 'v18.16.0'
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          single-commit: true
          branch: gh-pages
          folder: typedoc

